Connecting To MongoDB and building API for first AddNewPost
taljacob2/colman-advanced-web-apps-ex-1 pull request #8
Opened 2024-11-25 16:49 UTC by mevo0108

closes #1

2024-11-25 17:51 UTC, taljacob2 requested changes
Overall great job! 💯 

A few modifications are required for final approval.
Please make them, and we're done!

2024-11-25 17:51 UTC, taljacob2 commented on app_ex1.js
> +
Please rename this file to `app.js`

2024-11-25 17:51 UTC, taljacob2 commented on controllers/post.js
> +        res.status(400).send(error);
Should we change this `send(error)` to `send(error.message)` to match line 15?

2024-11-25 17:51 UTC, taljacob2 commented on app_ex1.js
> +const app = express();
Please accept this code, so the `.env` file would be able to expand a variable by other variables.

```suggestion
const dotenv = require("dotenv");
const dotenvExpand = require("dotenv-expand");
dotenvExpand.expand(dotenv.config());
```

Take note that you should install the `dotenv-expand` package with `npm i dotenv-expand`, and commit the updated `package.json`.

Then, for example you could use in your `.env`:

```sh
USERNAME=John
HELLO_MESSAGE="Hello ${USERNAME}"
```

2024-11-25 17:51 UTC, taljacob2 commented on models/posts_model.js
> +});
Please accept this code, so the post document wouldn't have the generated `__v` property.

```suggestion
}, {
    versionKey: false,
});
```

Example Before:
```json
{
  "_id": "6744b4dea4ce2442aeddf377",
  "title": "Post 1",
  "content": "This is my first post",
  "owner": "Mevorah",
  "__v": 0
}
```

Example After:
```json
{
  "title": "Post 1",
  "content": "This is my first post",
  "owner": "Mevorah",
  "_id": "6744b55259e23afd32c6e2ac"
}
```

2024-11-25 17:51 UTC, taljacob2 commented on controllers/post.js
> +const postModel = require('../models/posts_model');
Please rename this file to `posts_controller.js`

2024-11-25 17:51 UTC, taljacob2 commented on app_ex1.js
> +const port = process.env.PORT;
Please add a new file called `.env.template` in the root directory of the project with the following content:

```sh
PORT=<PORT>
DB_CONNECTION=<DB_CONNECTION>
```

So other people would know that they are required to create an `.env` file with these variables to run the application.

2024-11-25 18:18 UTC, mevo0108 commented on app_ex1.js
> +
no PB

2024-11-25 18:30 UTC, mevo0108 commented on app_ex1.js
> +const app = express();
no problem i would be happy for more info about it :)

2024-11-25 18:34 UTC, mevo0108 commented on controllers/post.js
> +const postModel = require('../models/posts_model');
done

2024-11-25 18:37 UTC, mevo0108 reviewed
finish to pass on all the review .
waiting for your approved to add the new file that you ask me for (.env.tamplate) on a new assignement (TODO)

2024-11-25 18:39 UTC, mevo0108 reviewed
@taljacob2

2024-11-25 19:02 UTC, taljacob2 commented on routes/posts_routes.js
> +
Please fix this typo of renaming posts controller:

```suggestion
const Post = require('../controllers/posts_controller');
```

2024-11-25 19:20 UTC, taljacob2 approved these changes
Approved, need to add `.env.template` at #9

2024-11-25 19:21 UTC, merged

2024-11-29 07:30 UTC, taljacob2 commented on app_ex1.js
> +const port = process.env.PORT;
Resolved in #9